---
title: "Chr 3 Story"
output: html_notebook
---

```{r message=FALSE}
library(qtl2shiny)
library(gridBase)
library(grid)
```

```{r}
source(file.path(system.file("doqtl2/setup.R", 
                             package = "qtl2shiny")))
```

### Setup Phenotypes and Region

```{r}
phe_par <- list(pheno_names = "AA_G83_ins_secrete")
win_par <- list(chr_id = "3",
                peak_Mbp = 140,
                window_Mbp = 5)
```

```{r}
analyses_df <- analyses_tbl %>%
  filter(pheno %in% phe_par$pheno_names)
phe_df <- get_pheno(pheno_data,
                    analyses_df %>%
                      distinct(pheno, .keep_all=TRUE))
cov_mx <- get_covar(covar, analyses_df)
K_chr <- K[win_par$chr_id]
```

### Haplo Analysis

```{r}
probs_obj <- read_probs(win_par$chr_id, datapath)
```

```{r}
scan_obj <- scan1(probs_obj, phe_df, K_chr, cov_mx)
```

```{r}
scan_window <- win_par$peak_Mbp + 
  c(-1,1) * win_par$window_Mbp
```

#### Allele LOD Scan

```{r}
pdf("images/scan_3.pdf", width=9,height=6)
show_peaks(win_par$chr_id, scan_obj, mytitle="")
dev.off()
```

#### Allele Effect Scan

```{r}
eff_obj <- listof_scan1coefCC(phe_df, cov_mx, probs_obj, K_chr)
```

```{r}
pdf("images/scan_3_effect.pdf", width=10,height=6)
par(mfrow=c(1,2))
show_peaks(win_par$chr_id, scan_obj, mytitle="", 
           xlim = scan_window)
plot_eff(phe_par$pheno_names, scan_obj, eff_obj, scan_window)
dev.off()
```

#### SNP Scan

```{r}
snpprobs_obj <- get_snpprobs(win_par$chr_id, 
                   win_par$peak_Mbp, 
                   win_par$window_Mbp,
                   phe_par$pheno_names, 
                   probs_obj,
                   datapath)
```

```{R}
snp_action <- "basic"
```

```{r}
snp_scan_obj <- scan1(snpprob_collapse(snpprobs_obj,
                                       snp_action), 
                      phe_df, K_chr, cov_mx)
```

```{r}
top_snps_tbl <- get_top_snps_tbl(snp_scan_obj)
```

```{r}
gene_exon_tbl <- 
  get_gene_exon_snp(top_snps_tbl,
                    file.path(datapath, "mgi_db.sqlite"))
```

#### SNP Association & Allele Patterns

```{r}
pdf("images/snp_assoc_3_pattern.pdf", width=10,height=6)
par(mfrow=c(1,2))
top_snp_asso(phe_par$pheno_names, snp_scan_obj, 
             scan_window, snp_action)
plot.new()
vps <- baseViewports()
pushViewport(vps$figure)
vp1 <-plotViewport(c(1,1,1,1)) 
p1 <- top_pat_plot(phe_par$pheno_names, snp_scan_obj, 
             scan_window, TRUE,
             snp_action = snp_action)
print(p1,vp = vp1)
dev.off()
```

#### Diplo Probabilities

```{r}
probs36_obj <- read_probs36(win_par$chr_id, 
                            scan_window[1],
                            scan_window[2],
                            datapath)
```

```{r}
snpprobs36_obj <- get_snpprobs(win_par$chr_id, 
                   win_par$peak_Mbp, 
                   win_par$window_Mbp,
                   phe_par$pheno_names, 
                   probs36_obj,
                   datapath)
```

```{r}
diplos <- dimnames(probs36_obj$probs[[1]])[[2]]
haplos <- unique(unlist(str_split(diplos, "")))
```

#### Diplo add+dom for SNP Association

```{r}
snp_action <- "add+dom"
```

```{r}
snp_scan36_obj <- scan1(snpprob_collapse(snpprobs36_obj,
                                         snp_action), 
                        phe_df, K_chr, cov_mx)
```

```{r}
pdf(paste0("images/snp_assoc_3_pattern_",
           snp_action, ".pdf"),
    width=10,height=6)
par(mfrow=c(1,2))
top_snp_asso(phe_par$pheno_names, snp_scan36_obj, 
             scan_window, snp_action)
plot.new()
vps <- baseViewports()
pushViewport(vps$figure)
vp1 <-plotViewport(c(1,1,1,1)) 
p1 <- top_pat_plot(phe_par$pheno_names, snp_scan36_obj, 
             scan_window, TRUE,
             snp_action = snp_action)
print(p1,vp = vp1)
dev.off()
```

#### Diplo SNP Allele Patterns & LODs

```{r}
snp_action <- "additive"
pattern <- "BEFGH:ACD"
```

```{r}
source("diplo_calc.R")
```

```{r}
snp_action <- "additive"
pattern <- "BFGH:ACDE"
```

```{r}
source("diplo_calc.R")
```

```{r}
snp_action <- "recessive"
pattern <- "ABCEFGH:D"
```

```{r}
source("diplo_calc.R")
```

```{r}
snp_action <- "dominant"
pattern <- "ABCDEFH:G"
```

```{r}
source("diplo_calc.R")
```

