---
title: "Recla qtl2shiny Demo"
author: "Brian S. Yandell"
date: "2/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a demo of the Recla et al. dataset using functionality of [R/qtl2shiny](https://github.com/byandell/qtl2shiny) shown in <http://www.stat.wisc.edu/~yandell/software/qtl2shiny>. We assume that the 
[CCmouse.Rmd](https://github.com/byandell/qtl2shiny/blob/master/inst/doc/CCmouse.Rmd) and 
[Recla.Rmd](https://github.com/byandell/qtl2shiny/blob/master/inst/doc/Recla.Rmd)
scripts have already been run to put data in the `CCmouse` directory.

```{r message=FALSE}
library(dplyr)
library(qtl2)
library(qtl2ggplot)
library(qtl2pattern)
library(ggplot2)
```

```{r}
project_info <- data.frame(project = "Recla",
                           taxa = "CCmouse",
                           directory = ".",
                           stringsAsFactors = FALSE)
```

```{r}
(project_dir <- file.path(project_info$directory, 
                          project_info$taxa, 
                          project_info$project))
```

```{r}
dir.exists(project_dir)
```

List files for the taxa and for the project.

```{r}
list.files(project_info$taxa)
```

```{r}
list.files(project_dir)
```

```{r}
list.files(file.path(project_dir, "genoprob")) 
```

## Choose Region and Phenotype

```{r}
# See shinyHotspot.R
hotspots <- readRDS(file.path(project_dir, "hotspot.rds"))
```

```{r}
# See shinyHotspot.R
autoplot(hotspots$scan, hotspots$map)
```

```{r}
# See shinyHotspot.R
(hot_sum <- summary(hotspots$scan, hotspots$map) %>%
  filter(pheno == "all") %>%
  rename(count = lod) %>%
  select(-marker) %>%
  arrange(desc(count)))
```

```{r}
chr_id <- as.character(hot_sum$chr[1])
pos_Mbp <- hot_sum$pos[1]
window_Mbp <- 5
start_val <- pos_Mbp - window_Mbp
end_val <- pos_Mbp + window_Mbp
```

```{r}
# See shinyHotspot.R
autoplot(hotspots$scan, hotspots$map, chr = chr_id)
```

```{r}
# See shinyMain.R
peaks <- readRDS(file.path(project_dir, "peaks.rds")) %>%
  filter(chr == chr_id,
         pos >= start_val,
         pos <= end_val)
```

```{r}
# See shinyPhenos.R
(peaks <- peaks %>%
  select(pheno, chr, pos, lod) %>%
  arrange(desc(lod)))
```

```{r}
pheno_name <- peaks$pheno[1]
```

#### Phenotype Data

```{r}
# See shinyMain.R
(analyses <- readRDS(file.path(project_dir, "analyses.rds")) %>%
  filter(pheno == pheno_name))
```

```{r}
# See shinyMain.R
(pheno_data <- readRDS(file.path(project_dir, "pheno_data.rds")) %>%
   pheno_trans(analyses$pheno, 
               analyses$transf,
               analyses$offset,
               analyses$winsorize)) %>% 
  head
```

```{r}
# See shinyMain.R
(covar <- readRDS(file.path(project_dir, "covar.rds")) %>%
  get_covar(analyses)) %>%
  head
```

## Genome Scan

```{r}
# See shinyMain.R
kinship <- readRDS(file.path(project_dir, "kinship.rds"))[chr_id]
```

```{r}
# See shinyProbs.R and Recla.Rmd
query_probs <- create_probs_query_func(project_dir)
probs_obj <- query_probs(chr_id, start_val, end_val)
```

```{r}
names(probs_obj)
dim(probs_obj$probs)
```

```{r}
# See shinyScanCoef.R
scan_obj <- scan1_covar(pheno_data, covar, probs_obj$probs, kinship,
                        analyses)
```

```{r}
autoplot(scan_obj, probs_obj$map)
```

```{r}
summary(scan_obj, probs_obj$map)
```

```{r}
find_peaks(scan_obj, probs_obj$map)
```

```{r}
addcovar <- covar_df_mx(covar)
eff_obj <- scan1coef(probs_obj$probs, pheno_data, kinship, addcovar)
```

```{r}
autoplot(eff_obj, probs_obj$map) +
  geom_vline(xintercept = peaks$pos[1], linetype = "dashed")
```


